import {
  Ishan,
  Arti,
  Siddhi,
  Daksh,
  Avani,
  Aashish,
  Janvi,
  Suhani,
  Mahi,
  Hrithema,
  Manisha,
  Saurabh,
  Shanvika,
  Kritika,
  Tavishi,
  Riddhi,
  Anant,
  Lakshya,
  AyushTiwari,
  Amritanshu,
  Akshat,
  Shreyashi,
  Harsh,
  Preethi,
  Anushka,
  Gnana,
  Anshika,
  Amir,
  Yash,
  Sparsh,
  Harshit,
  Pragati,
  Ojasva,
  Rishabh,
  Siddhant,
  Rishita,
  Namit,
  Sneha,
  Maulik,
  Sandeep,
  Himanshu,
  Anurudh,
  Navya,
  Saanvi,
  Muskan,
  Plansha,
  Saumya,
  Dhairya,
  Abhilash,
  Warsi,
  Vatsal,
  SoumyaG,
  Sameer,
  Vaaruni,
} from "../../assets/TeamAssets";

// Techy Golden Placeholder SVG
const placeholderImage = `data:image/svg+xml,%3Csvg width='400' height='500' viewBox='0 0 400 500' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='400' height='500' fill='black'/%3E%3Cpath d='M200 150c44.183 0 80 35.817 80 80s-35.817 80-80 80-80-35.817-80-80 35.817-80 80-80zm0 180c66.274 0 120 53.726 120 120v20H80v-20c0-66.274 53.726-120 120-120z' fill='%23f59e0b' fill-opacity='0.2'/%3E%3Cpath d='M30 30l340 440M370 30L30 470' stroke='%23f59e0b' stroke-width='1' stroke-opacity='0.1'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='monospace' font-size='14' fill='%23f59e0b' fill-opacity='0.5' letter-spacing='4'%3EPHOTO_PENDING%3C/text%3E%3Crect x='20' y='20' width='360' height='460' fill='none' stroke='%23f59e0b' stroke-width='1' stroke-opacity='0.2'/%3E%3C/svg%3E`;

const TeamData = () => [
  {
    id: 1,
    name: "Content Team",
    members: [
      { name: "Ishan Rai", position: "Lead", image: Ishan },
      { name: "Siddhi Agarwal", position: "Core Member", image: Siddhi },
      { name: "Arti Sharma", position: "Core Member", image: Arti },
      { name: "Daksh Jain", position: "Core Member", image: Daksh },
      { name: "Suhani Boxi", position: "Core Member", image: Suhani },
      { name: "Aashish Singh", position: "Core Member", image: Aashish },
      { name: "Avani", position: "Core Member", image: Avani },
      { name: "Mahi Pandey", position: "Core Member", image: Mahi },
      { name: "Janvi Kalra", position: "Core Member", image: Janvi },
    ],
  },
  {
    id: 2,
    name: "Design Team",
    members: [
      { name: "Saurabh Sharma", position: "Lead", image: Saurabh },
      { name: "Hrithema", position: "Co-lead", image: Hrithema },
      { name: "Manisha Mitra", position: "Core Member", image: Manisha },
      { name: "Riddhi Mhadgut", position: "Core Member", image: Riddhi },
      { name: "Lakshya Agarwal", position: "Core Member", image: Lakshya },
      { name: "Kritika Mohan", position: "Core Member", image: Kritika },
      { name: "Tavishi Umrao", position: "Core Member", image: Tavishi },
      { name: "Shanvika Raj", position: "Core Member", image: Shanvika },
    ],
  },
  {
    id: 3,
    name: "Event Team",
    members: [
      { name: "Anant Yadav", position: "Lead", image: Anant },
      { name: "Ayush Tiwari", position: "Co-lead", image: AyushTiwari, objectPosition: "top" },
      { name: "Harsh Raj", position: "Core Member", image: Harsh },
      { name: "Akshat Raj", position: "Core Member", image: Akshat },
      { name: "Shaion Dutta", position: "Core Member", image: placeholderImage },
      { name: "Bangalore Preethi", position: "Core Member", image: Preethi },
      { name: "Gnana Sushanth Reddy T", position: "Core Member", image: Gnana },
      { name: "Amritanshu Kumar Singh", position: "Core Member", image: Amritanshu },
      { name: "Shreyashi", position: "Core Member", image: Shreyashi },
      { name: "Anushka Verma", position: "Core Member", image: Anushka },
      { name: "Priya Jha", position: "Core Member", image: placeholderImage },
    ],
  },
  {
    id: 4,
    name: "Media Team",
    members: [
      { name: "Yash Sushil", position: "Lead", image: Yash },
      { name: "Issac Jogi", position: "Core Member", image: placeholderImage },
      { name: "Anshika Singh", position: "Core Member", image: Anshika },
      { name: "Sparsh Sachan", position: "Core Member", image: Sparsh },
      { name: "Mohd Amir Anwar Khan", position: "Core Member", image: Amir },
    ],
  },
  {
    id: 5,
    name: "PR Team",
    members: [
      { name: "Pragati Singh", position: "Lead", image: Pragati },
      { name: "Rishabh Jhang", position: "Co-lead", image: Rishabh },
      { name: "Harshit Jaiswal", position: "Core Member", image: Harshit },
      { name: "Ojasva Pandey", position: "Core Member", image: Ojasva },
      { name: "Siddhant Ghosh", position: "Core Member", image: Siddhant },
      { name: "Ishant Gupta", position: "Core Member", image: placeholderImage },
    ],
  },
  {
    id: 6,
    name: "Social Media Team",
    members: [
      { name: "Rishita Mehta", position: "Lead", image: Rishita },
      { name: "Anurudh Pratap Singh", position: "Core Member", image: Anurudh },
      { name: "Maulik Saini", position: "Core Member", image: Maulik },
      { name: "Navya Sethi", position: "Core Member", image: Navya },
      { name: "Sandeep Ganesh", position: "Core Member", image: Sandeep },
      { name: "Himanshu Rajpoot", position: "Core Member", image: Himanshu },
      { name: "Sneha Rakundla", position: "Core Member", image: Sneha },
      { name: "Namit Jain", position: "Core Member", image: Namit },
      { name: "Saanvi Awasthi", position: "Core Member", image: Saanvi },
    ],
  },
  {
    id: 7,
    name: "Technical Team",
    members: [
      { name: "Dhairya Gothi", position: "Lead", image: Dhairya },
      { name: "Muskan Srivastav", position: "Co-lead", image: Muskan },
      { name: "Harshvardhan Jajoo", position: "Core Member", image: placeholderImage },
      { name: "Soumya Ghosh", position: "Core Member", image: SoumyaG },
      { name: "Saumya Sopan Bari", position: "Core Member", image: Saumya },
      { name: "Vatsal Mahajan", position: "Core Member", image: Vatsal },
      { name: "Shaikh Mohammad Warsi", position: "Core Member", image: Warsi },
      { name: "Abhilash Shah", position: "Core Member", image: Abhilash },
      { name: "Plansha", position: "Core Member", image: Plansha },
      { name: "Sameer Chaudhary", position: "Core Member", image: Sameer },
    ],
  },
  {
    id: 8,
    name: "Anchor Team",
    members: [
      { name: "Vaaruni Sharma", position: "Lead", image: Vaaruni },
    ],
  },
];

export default TeamData;
